### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 8: ordinal not in range(128)

### ISSUE THREAD

**Issue by best-tech** [gruns/gitauthors#1]
`py gitauthors https://github.com/vibora-io/vibora
Traceback (most recent call last):
  File "gitauthors", line 145, in <module>
    main()
  File "gitauthors", line 139, in main
    out = gitauthors(url)
  File "gitauthors", line 130, in gitauthors
    lines.append(tmp.format(name, email, numCommits, latestCommitDate))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 8: ordinal not in range(128)`

**Comment by gruns** [comment]
Fixed in GitAuthors v0.1.1.

```
$ gitauthors https://github.com/vibora-io/vibora 
Frank Vieira                frank@frankvieira.com.br                      103 commits, latest on Jul 14, 2018
JakeScott                   jscott35@uic.edu                                3 commits, latest on Jun 23, 2018
Philip Xu                   pyx@xrefactor.com                               3 commits, latest on Jun 19, 2018
Daniel Däschle              daniel.daeschle@gmail.com                       3 commits, latest on Jul 15, 2018
...
```

Update with

```
$ pip install gitauthors --upgrade
```

Thank you for reporting this bug, Denis. Don't hesitate to let me know if
there's anything else I can do for you.
